vscode_version  = "1.87.2"

[[extensions]]
publisher_name = "aaron-bond"
extension_name = "better-comments"

[[extensions]]
publisher_name = "charliermarsh"
extension_name = "ruff"

[[extensions]]
publisher_name = "corker"
extension_name = "vscode-micromamba"

[[extensions]]
publisher_name = "github"
extension_name = "copilot"

[[extensions]]
publisher_name = "github"
extension_name = "copilot-chat"

[[extensions]]
publisher_name = "james-yu"
extension_name = "latex-workshop"

[[extensions]]
publisher_name = "jnoortheen"
extension_name = "nix-ide"

[[extensions]]
publisher_name = "k--kato"
extension_name = "intellij-idea-keybindings"

[[extensions]]
publisher_name = "ms-python"
extension_name = "python"

[[extensions]]
publisher_name = "ms-toolsai"
extension_name = "jupyter"

[[extensions]]
publisher_name = "ms-toolsai"
extension_name = "jupyter-keymap"

[[extensions]]
publisher_name = "ms-toolsai"
extension_name = "jupyter-renderers"

[[extensions]]
publisher_name = "ms-toolsai"
extension_name = "vscode-jupyter-cell-tags"

[[extensions]]
publisher_name = "ms-toolsai"
extension_name = "vscode-jupyter-slideshow"

[[extensions]]
publisher_name = "naumovs"
extension_name = "color-highlight"

[[extensions]]
publisher_name = "njpwerner"
extension_name = "autodocstring"

[[extensions]]
publisher_name = "patbenatar"
extension_name = "advanced-new-file"

[[extensions]]
publisher_name = "pkief"
extension_name = "material-icon-theme"

[[extensions]]
publisher_name = "znck"
extension_name = "grammarly"
